# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1
metadata:
  category: Automation
  name: Home Assistant
  version: 2022.4.4
  tagline: Home automation that puts local control & privacy first
  description: >-
    Open source home automation that puts local control and privacy first,
    powered by a worldwide community of tinkerers and DIY enthusiasts. Home
    Assistant integrates with over a thousand different devices and services.
    Once you have integrated all your devices at home, you can unleash Home
    Assistant’s advanced automation engine to make your home work for you.
    Examples:


    - Turn on the light when the sun sets or when coming home

    - Alert you when you leave your garage door open

    All your smart home data stays local. Home Assistant communicates with your devices locally, and will fallback to pulling in data from the cloud if there is no other option. No data is stored in the cloud, and everything is processed locally.
  developer: Home Assistant
  website: https://home-assistant.io
  dependencies: []
  repo: https://github.com/home-assistant/core
  support: https://community.home-assistant.io
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
containers:
  - name: server
    image: homeassistant/home-assistant:2022.4.4@sha256:ae4e3e231458d49280a0b8746217f000480f8f3358e4e34a8a4e784f54a1b3e4
    port: 8123
    data:
      - data:/config
