version: 3
metadata:
  category: Development
  name: Gitea
  version: 1.18.3
  tagline: A painless self-hosted Git service
  description: |-
    Gitea is a painless self-hosted Git service. It is similar to GitHub, Bitbucket, and GitLab. It is a community managed lightweight code hosting solution written in Go. Gitea's minimal requirements allow it to run seamlessly on inexpensive hardware like a Raspberry Pi. Features:

    - Fully self-hosted and private
    - Issue tracker
    - Account/Organization/Repository management
    - Tor support
    - Repository Git hooks/deploy keys
    - Repository issues, pull requests and wiki
    - Add/Remove repository collaborators
    - Gravatar and custom source
    - Admin panel
  developers:
    Gitea: https://gitea.io/en-us/
  dependencies: []
  repo: https://github.com/go-gitea/gitea
  support: https://discourse.gitea.io
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
containers:
- name: main
  image: gitea/gitea:1.18.3@sha256:c4d3a9311a2c1038b1e5953d95060d245ecaedf5f1f9758b0b65aeab0fddbba0
  data:
  - data/gitea/config:/etc/gitea
  - data/gitea/data:/var/lib/gitea
  environment:
    GITEA__database__DB_TYPE: mysql
    GITEA__server__SSH_DOMAIN: ${APP_DOMAIN}
    GITEA__server__HTTP_PORT: ${APP_GITEA_MAIN_PORT}
    GITEA__database__PASSWD: moneyprintergobrrr
    GITEA__database__USER: gitea
    GITEA__database__HOST: ${APP_GITEA_DB_IP}:3306
    GITEA__security__INSTALL_LOCK: 'true'
    GITEA__server__DOMAIN: ${APP_DOMAIN}
    GITEA__server__SSH_LISTEN_PORT: 2222
    GITEA__server__SSH_PORT: 2222
    GITEA__database__NAME: gitea
    GITEA__server__START_SSH_SERVER: 'true'
  requiredPorts:
  - 2222
  user: 1000:1000
- name: db
  image: mariadb:10.6.4@sha256:4bbee12b1adf299211f844ebbe89563675c46965470dcfa40f5278d63c56d030
  data:
  - data/db:/var/lib/mysql
  environment:
    MYSQL_DATABASE: gitea
    MYSQL_ROOT_PASSWORD: gitea
    MYSQL_PASSWORD: moneyprintergobrrr
    MYSQL_USER: gitea
  user: 1000:1000
