# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v3.yml

version: 3
metadata:
  category: Development
  name: Gitea
  version: 1.17.1
  tagline: A painless self-hosted Git service
  description: >-
    Gitea is a painless self-hosted Git service. It is similar to GitHub,
    Bitbucket, and GitLab. It is a community managed lightweight code hosting
    solution written in Go. Gitea's minimal requirements allow it to run
    seamlessly on inexpensive hardware like a Raspberry Pi. Features:


    - Fully self-hosted and private

    - Issue tracker

    - Account/Organization/Repository management

    - Tor support

    - Repository Git hooks/deploy keys

    - Repository issues, pull requests and wiki

    - Add/Remove repository collaborators

    - Gravatar and custom source

    - Admin panel
  developers:
    Gitea: https://gitea.io/en-us/
  dependencies: []
  repo: https://github.com/go-gitea/gitea
  support: https://discourse.gitea.io
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
containers:
  - image: gitea/gitea:1.17.1-rootless@sha256:94a1225961d5af613e965948bd0ec8ddf2e43a93114660498ee6d292a3ccdbe2
    user: 1000:1000
    requiredPorts:
      - 2222
    environment:
      GITEA__security__INSTALL_LOCK: "true"
      GITEA__server__DOMAIN: ${APP_DOMAIN}
      GITEA__server__HTTP_PORT: ${APP_GITEA_SERVER_PORT}
      GITEA__server__SSH_DOMAIN: ${APP_DOMAIN}
      GITEA__server__SSH_PORT: 2222
      GITEA__server__SSH_LISTEN_PORT: 2222
      GITEA__server__START_SSH_SERVER: "true"
      GITEA__database__DB_TYPE: mysql
      GITEA__database__HOST: ${APP_GITEA_DB_IP}:3306
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: moneyprintergobrrr
    name: main
    data:
      - data/gitea/config:/etc/gitea
      - data/gitea/data:/var/lib/gitea
  - image: mariadb:10.6.4@sha256:4bbee12b1adf299211f844ebbe89563675c46965470dcfa40f5278d63c56d030
    user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: moneyprintergobrrr
      MYSQL_DATABASE: gitea
    name: db
    data:
      - data/db:/var/lib/mysql
